import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "OptiLVAD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
