import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "OptiLVAD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-screen overflow-hidden">
      <body
        className={`flex min-h-full h-screen flex-col bg-cover bg-gradient-to-b from-[#171617] to-[#CF4B07] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
