version: "2"
services:
  orthanc:
    image: orthancteam/orthanc
    ports: ["80:8042"]
    environment:
      ORTHANC__REGISTERED_USERS: |
        {"demo": "demo"}
backend:
  build:
    context:
    dockerfile: Dockerfile
  ports:
    - "8000:8000"
  depends_on:
    - orthanc
